{% set name = "tomtoolkit" %}
{% set version = "2.25.2" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tomtoolkit-{{ version }}.tar.gz
  sha256: b8df94427aa86d7f83d48ebcfccc7e802c26d5f21179651685c67240c1450164

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0,<3.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >1.24,<2.2
    - astroquery <1
    - astroplan >=0.8,<0.11
    - astropy-base >=5.3.3,<7
    - django <5
    - djangorestframework >=3.15,<4
    - django-bootstrap4 >3,<25
    - beautifulsoup4 <5
    - django-contrib-comments >=2.0,<3.0
    - django-crispy-forms >=2.0,<3.0
    - crispy-bootstrap4 >=2023.1,<2024.11
    - django-extensions >=3.0.0,<4.0.0
    - django-filter >=23,<25
    - django-gravatar2 >=1.0.0,<2.0.0
    - django-guardian >=2.0.0,<3.0.0
    - django-htmx >=1.0.0,<2.0.0
    - django-tasks >=0.6.1,<0.7.0
    - fits2image >=0.4,<0.5
    - markdown <4
    - pillow >9.2,<12.0
    - plotly <6
    - python-dateutil <3
    - requests <3
    - specutils >=1.17,<2
    - importlib-resources >=6.4.5,<6.5.0

test:
  requires:
    - python {{ python_min }}
    - pip
    - pipdeptree
  imports:
    - tom_targets
    - tom_observations
  commands:
    - pipdeptree

about:
  home: https://github.com/TOMToolkit/tom_base
  summary: TOM Toolkit and base modules
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davner
    - phycodurus
    - jchate6
